# Generated by Django 6.0 on 2025-12-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="liked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reel",
            name="liked",
            field=models.BooleanField(default=False),
        ),
    ]
